### ISSUE TITLE
Incompatible with CoFHCore-1.7-revived

### ISSUE THREAD

**Issue by Omgise** [HowardZHY/LegacyCompatibilityUtils-1.7.10#1]
[fml-client-latest.log](https://github.com/user-attachments/files/16573697/fml-client-latest.log)
[fml-junk-earlystartup.log](https://github.com/user-attachments/files/16573698/fml-junk-earlystartup.log)

**Comment by HowardZHY** [comment]
尝试在模组jar的名字前加符号以优先加载，仅次于UniMixins

**Comment by Omgise** [comment]
把模组jar的名字改成`00compatlib-1.7.10.jar`仍旧崩溃
[fml-client-latest.log](https://github.com/user-attachments/files/16579439/fml-client-latest.log)
[fml-junk-earlystartup.log](https://github.com/user-attachments/files/16579440/fml-junk-earlystartup.log)

**Comment by HowardZHY** [comment]
> 把模组jar的名字改成`00compatlib-1.7.10.jar`仍旧崩溃 [fml-client-latest.log](https://github.com/user-attachments/files/16579439/fml-client-latest.log) [fml-junk-earlystartup.log](https://github.com/user-attachments/files/16579440/fml-junk-earlystartup.log)

[新建 好压 ZIP 压缩文件.zip](https://github.com/user-attachments/files/16581799/ZIP.zip)

测试这个行不行，如果不行二分法排查Mod罢

**Comment by Omgise** [comment]
那只能二分法排查了

**Comment by HowardZHY** [comment]
> 那只能二分法排查了

找到相关模组了吗

**Comment by Omgise** [comment]
> > 那只能二分法排查了
> 
> 找到相关模组了吗

没找到（

**Comment by HowardZHY** [comment]
有更多相关信息了吗？

无论如何，过早调用这个类的只能是CoreMod，不可能是普通Mod

**Comment by Omgise** [comment]
我删了很多mod，但是还是崩溃，你可以看看这些崩溃信息吗
[fml-client-latest.log](https://github.com/user-attachments/files/16818295/fml-client-latest.log)
[fml-junk-earlystartup.log](https://github.com/user-attachments/files/16818297/fml-junk-earlystartup.log)
[latest.log](https://github.com/user-attachments/files/16818298/latest.log)

**Comment by HowardZHY** [comment]
> 我删了很多mod，但是还是崩溃，你可以看看这些崩溃信息吗 [fml-client-latest.log](https://github.com/user-attachments/files/16818295/fml-client-latest.log) [fml-junk-earlystartup.log](https://github.com/user-attachments/files/16818297/fml-junk-earlystartup.log) [latest.log](https://github.com/user-attachments/files/16818298/latest.log)

再删，还是太多；日志显示mega.blendtronic居然是Java21编译的，无法加载？

还有，fml-junk-earlystartup.log是垃圾日志，不用发

**Comment by Omgise** [comment]
[fml-client-latest.log](https://github.com/user-attachments/files/16823752/fml-client-latest.log)

**Comment by HowardZHY** [comment]
> [fml-client-latest.log](https://github.com/user-attachments/files/16823752/fml-client-latest.log)

再删一些，还是无法判断

**Comment by Omgise** [comment]
找到最小的崩溃组合了，和COFHCore不兼容
这是COFHCore的源代码：https://github.com/FalsePattern/CoFHCore-1.7-revived
[fml-client-latest.log](https://github.com/user-attachments/files/16827097/fml-client-latest.log)

![image](https://github.com/user-attachments/assets/2ff5efba-6c72-49bc-a157-20eba059de72)

**Comment by Omgise** [comment]
@HowardZHY
