### ISSUE TITLE
Question - Mod development

### ISSUE THREAD

**Issue by mateus3c** [HowardZHY/LegacyCompatibilityUtils-1.7.10#2]
Hi! Your mod really caught my attention, I found it to be very interesting the way you made mods from past versions able to run on post versions. I was wondering, do you think something similar could be achieved in modern minecraft version such as 1.20.1/1.19
2?
For example, if removed classes and srg methods/fields from Minecraft and Forge 1.19.2 were re-added by a 1.20.1 Forge mod, would that, even if unstable, make 1.19.2 mods work on 1.20.1?
I dont have experience modding Minecraft but I do have some Java programming background and I really wanted to try making something like this but beforehand I wanted to ask you to see what's your thoughts and opinions regarding this, considering you have already successfully made this backwards compatibility possible :)

**Comment by HowardZHY** [comment]
> Hi! Your mod really caught my attention, I found it to be very interesting the way you made mods from past versions able to run on post versions. I was wondering, do you think something similar could be achieved in modern minecraft version such as 1.20.1/1.19 2? For example, if removed classes and srg methods/fields from Minecraft and Forge 1.19.2 were re-added by a 1.20.1 Forge mod, would that, even if unstable, make 1.19.2 mods work on 1.20.1? I dont have experience modding Minecraft but I do have some Java programming background and I really wanted to try making something like this but beforehand I wanted to ask you to see what's your thoughts and opinions regarding this, considering you have already successfully made this backwards compatibility possible :)

This _might_ be possible, but requires too much work, you can find the changes docs in

https://github.com/neoforged/.github/tree/main/primers

I'm not interested at working on any modern versions, especially modern Forge.
